
version: 2

models:
  - name: dim_destination_change_table
    description: "A starter dbt model"
    columns:
      - name: index
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
    
  - name: dim_transaction_change_table
    description: "A starter dbt model"
    columns:
      - name: index
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_original_change_table
    description: "A starter dbt model"
    columns:

      - name: index
        description: "The primary key for this table"
        tests:
          - unique
          - not_null